### ISSUE TITLE
pose_parameterization.h : Why is it set to the identity matrix in ComputeJacobian?

### ISSUE THREAD

**Issue by Aviana-Zheng** [i2Nav-WHU/IC-GVINS#11]
![y3LlIpYr2T](https://user-images.githubusercontent.com/75773971/211731514-dda32c65-e570-48ac-91f9-2566d3bfe1ea.jpg)
In ComputeJacobian, it is set to the identity matrix. 
The Jacobian derivation recommended in the ceres source code is like this：
![image](https://user-images.githubusercontent.com/75773971/211732283-7f40d908-cbbe-43f3-b732-4275d10e2d87.png)
![image](https://user-images.githubusercontent.com/75773971/211732426-4575e58c-08b7-4542-8c9c-aff36eca90e7.png)
Dr. Tang, how did you derive your formula? Thank you.

**Comment by thlsealight** [comment]
The rotation vector is used rather than the quaternion when calculating the Jacobian for each factor. Hence, we do not need to calculate the Jacobian in the PoseParameterization.
