### ISSUE TITLE
process has died [pid 13438, exit code 1]

### ISSUE THREAD

**Issue by qqstar-423** [i2Nav-WHU/IC-GVINS#12]
感谢你们的开源！
但是，我使用命令roslaunch ic_gvins ic_gvins.launch configfile:=/home/qqstar/catkin_loam/src/IC-GVINS/config/gvins.yaml出现问题，报错如下：
ERROR: flag 'logtostderr' was defined more than once (in files 'src/logging.cc' and '/home/qqstar/lib/glog/src/logging.cc').
[ic_gvins_node-2] process has died [pid 13164, exit code 1, cmd /home/qqstar/catkin_loam/devel/lib/ic_gvins/ic_gvins_ros __name:=ic_gvins_node __log:=/home/qqstar/.ros/log/8816be48-9891-11ed-83c4-cdbabb5b49ff/ic_gvins_node-2.log].
log file: /home/qqstar/.ros/log/8816be48-9891-11ed-83c4-cdbabb5b49ff/ic_gvins_node-2*.log

我的yaml文件如下：
outputpath: "/home/qqstar/catkin_loam/src/IC-GVINS/output/"
is_make_outputdir: true
其余参数均为默认，请问为何会出现这个问题呢

**Comment by thlsealight** [comment]
> 感谢你们的开源！ 但是，我使用命令roslaunch ic_gvins ic_gvins.launch configfile:=/home/qqstar/catkin_loam/src/IC-GVINS/config/gvins.yaml出现问题，报错如下： ERROR: flag 'logtostderr' was defined more than once (in files 'src/logging.cc' and '/home/qqstar/lib/glog/src/logging.cc'). [ic_gvins_node-2] process has died [pid 13164, exit code 1, cmd /home/qqstar/catkin_loam/devel/lib/ic_gvins/ic_gvins_ros __name:=ic_gvins_node __log:=/home/qqstar/.ros/log/8816be48-9891-11ed-83c4-cdbabb5b49ff/ic_gvins_node-2.log]. log file: /home/qqstar/.ros/log/8816be48-9891-11ed-83c4-cdbabb5b49ff/ic_gvins_node-2*.log
> 
> 我的yaml文件如下： outputpath: "/home/qqstar/catkin_loam/src/IC-GVINS/output/" is_make_outputdir: true 其余参数均为默认，请问为何会出现这个问题呢

从你的错误提示明显显示为glog的冲突问题，请自行解决。请参考README.md进行初始配置运行DEMO。
