### ISSUE TITLE
GNSS

### ISSUE THREAD

**Issue by yzybilibili** [i2Nav-WHU/IC-GVINS#14]
hello,  If GNSS is missing from the beginning, can the system support it?

**Comment by yzybilibili** [comment]
hello, i want to get the ground_truth of the building dataset. Can you ask where can get it?

**Comment by thlsealight** [comment]
> hello, i want to get the ground_truth of the building dataset. Can you ask where can get it?

The ground truth is provided together with the ROS bag. They are in the same directory in Baidu Cloud.

**Comment by yzybilibili** [comment]
thank you!!

**Comment by yzybilibili** [comment]
what is the meaning of these datas ?   /time/ /pos_x/ /pos_y/ /pos_z/ /ori_w/ /ori_x/ /ori_y/ /ori_z/?

**Comment by thlsealight** [comment]
> what is the meaning of these datas ? /time/ /pos_x/ /pos_y/ /pos_z/ /ori_w/ /ori_x/ /ori_y/ /ori_z/?

The ground truth file is defined as TUM trajectory format. Maybe you should read the document and the source code more carefully.

**Comment by nwpuyzy** [comment]
hello, I have read the source code and do not know how to map the odom timestamp to the timestamp of the current image (for example, in VINSmono, the header is passed in to ensure the timestamp is consistent)
