### ISSUE TITLE
运行roslaunch ic_gvins ic_gvins.launch时报错

### ISSUE THREAD

**Issue by sxshenxue123** [i2Nav-WHU/IC-GVINS#19]
在终端中中运行这句语句
`roslaunch ic_gvins ic_gvins.launch configfile:=/home/oak/gvins_ws/src/IC-GVINS/config/gvins.yaml`
报错
![Snipaste_2023-04-16_00-52-39](https://user-images.githubusercontent.com/61368570/232239132-d0f0c54e-2cd4-48b4-8b1c-938f21bdf389.png)
此时rviz可以打开，但tracking显示错误
![Snipaste_2023-04-16_00-54-34](https://user-images.githubusercontent.com/61368570/232239411-87110f85-62e6-4aca-857f-bc3c0bfd01ca.png)
此时也可以正常播放bag文件，把tracking topic切换到cam0正常
![Snipaste_2023-04-16_00-56-49](https://user-images.githubusercontent.com/61368570/232239670-865caeb0-15a4-4523-9fe1-70c817652d68.png)

**Comment by thlsealight** [comment]
请修改/home/oak/gvins_ws/src/IC-GVINS/config/gvins.yaml配置文件中的结果输出路径。

**Comment by sxshenxue123** [comment]
感谢你的解答
对不起，之前一直没看到output路径，刚才修改过了，还是会报错
![Snipaste_2023-04-16_22-12-48](https://user-images.githubusercontent.com/61368570/232318939-b5773779-f9cc-4ee5-bb12-887192fd654c.png)
浏览之前的issue好像说是glog冲突的问题，我又重新编译了下，发现确实有glog的报错
![Snipaste_2023-04-16_22-04-44](https://user-images.githubusercontent.com/61368570/232319046-0f5c7cb1-ed59-45ae-a45e-858cdc5cb40c.png)
我不太懂该怎么解决这个glog冲突的问题

**Comment by thlsealight** [comment]
Ceres依赖glog，你大概需要重新编译ceres，确保你使用的是同一个glog。-------- 原始邮件 --------发件人： sxshenxue123 ***@***.***>日期： 2023年4月16日周日 22:16收件人： i2Nav-WHU/IC-GVINS ***@***.***>抄送： hailiang ***@***.***>, State change ***@***.***>主    题： Re: [i2Nav-WHU/IC-GVINS] 运行roslaunch ic_gvins ic_gvins.launch时报错 (Issue #19)
感谢你的解答
对不起，之前一直没看到output路径，刚才修改过了，还是会报错

浏览之前的issue好像说是glog冲突的问题，我又重新编译了下，发现确实有glog的报错

我不太懂该怎么解决这个glog冲突的问题

**Comment by bainature** [comment]
请问解决了吗 ，我也遇到这个问题了

**Comment by Oakshen** [comment]
已经解决了，具体请看这篇文章
https://blog.csdn.net/weixin_44002696/article/details/130211310?spm=1001.2014.3001.5501
