### ISSUE TITLE
关于几个“error”的原因和解决方法

### ISSUE THREAD

**Issue by 147longlong** [i2Nav-WHU/IC-GVINS#20]
你好！近期在运行贵校开源的IC-GVINS时，原有urban38数据集可以实现，但我们采用自己采集的数据集时，出现了三个问题。虽然已经初步了解了基本源码，但依旧没有找到问题所在，故望请指导。

- 1. IC-GVINS是否要求静止时候进行初始化？为什么会在零速初始化后近十秒不进行融合处理（在此十秒汽车已经开始运动），出现“raw data time **  ** **”如下图所示：

<img width="500" alt="image" src="https://user-images.githubusercontent.com/120914976/232402007-31095101-a2df-48f0-930f-df6d3ef63144.png">

- 2.外参在刚开始时候估计过大，导致轨迹偏差过大。之后虽然会回到正常轨迹，但想请问这种问题是因为问题1导致的吗？跑出来的轨迹如下图所示，车辆从右上角开始运动，之后又会到右上角，位姿偏差的原因是因为外参估计过大导致的。
<img width="895" alt="image" src="https://user-images.githubusercontent.com/120914976/232402857-bf650110-e7f5-4e28-9b46-afe76260935b.png">

- 3.经常可以遇到“wrong matching time node ** to **“的报错，我想知道这种报错的大致原因是什么，以及对应解决方法是什么

-下方是所用的配置文件，外参已修改，imu坐标系也调整过：
[syl_ic_gvins.txt](https://github.com/i2Nav-WHU/IC-GVINS/files/11247018/syl_ic_gvins.txt)

**Comment by thlsealight** [comment]
你好，针对你描述的问题，我只能根据经验作出解释，毕竟你的数据集我完全不了解：
1、IC-GVINS不需要静止初始化，反而需要依靠车辆动态获得初始的航向角，当然静止有利于初始零偏估计和水平姿态角确定。零速的判定有其阈值，你给的日志只有一秒的零速判定成功，后续是否静止不明确。初始化成功是根据GNSS定位判断的速度大小，速度必须要大于0.5m/s。

2、问题2和问题3出现说明系统运行再不正确的配置下，根据经验我只能提出几点建议：
1）确保你的IMU数据采样稳定连续，不存在大量丢数情况；
2）确保你的IMU噪声参数设定合理，根据IC-GVINS开源的数据集机器人或者KAIST数据集给的IMU的参数，对比你的IMU，选择一个设定，先不要自己设定。
3）确保你的GNSS定位的协方差设定合理，能够基本反映定位情况，而不是一个固定的值；
4）你的相机的分辨率较低，意味着影响关键帧的选择，track_min_parallax应该设置为10较为合理。需要注意的时，特征三角化的时候也卡了像素视差，这就很容易在你的数据集造成特征无法三角化。

这部分内容已超出本开源代码的支持范畴，我将直接关闭这个issue。
