### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ZJJ2022415** [i2Nav-WHU/IC-GVINS#23]
请问运行kaist数据集报错是为什么
![QQ图片20230420172128](https://user-images.githubusercontent.com/103757590/233321166-b337c41a-3279-4227-81f1-712a0c93d1e0.jpg)

**Comment by thlsealight** [comment]
如日志显示，请正确安装glog，重新编译ceres-solver以及IC-GVINS。

此issue为环境配置问题，与IC-GVINS系统本身无关，我将直接关闭这个issue。
