### ISSUE TITLE
请问模型是否有建图的功能？

### ISSUE THREAD

**Issue by JiangWeiHn** [i2Nav-WHU/IC-GVINS#26]
我通过调整imu噪声的参数，现在能跑完我采集的数据了，我看到了机器人跑的轨迹。请问模型是否考虑了建图，根据轨迹识别道路。为下次运行跑同样的地图提供帮助？

**Comment by thlsealight** [comment]
IC-GVINS不具备建图功能，具体可以自行阅读源代码。我将直接关闭这个issue。
