### ISSUE TITLE
[ic_gvins_node-2] process has died [pid 26173, exit code -11, cmd /home/bobododo/GNC/SLAM/gvins_ws/devel/lib/ic_gvins/ic_gvins_ros __name:=ic_gvins_node __log:=/home/bobododo/.ros/log/774a84ba-2f1d-11ed-b79f-645d86a8c9dd/ic_gvins_node-2.log]. log file: /home/bobododo/.ros/log/774a84ba-2f1d-11ed-b79f-645d86a8c9dd/ic_gvins_node-2*.log

### ISSUE THREAD

**Issue by bobododosjl** [i2Nav-WHU/IC-GVINS#3]
how to solve this issue

**Comment by thlsealight** [comment]
> how to solve this issue

I can't see any useful message. Maybe you should check your configuration file. Also, you need change the output path in the configuration file.

**Comment by bobododosjl** [comment]
> > how to solve this issue
> 
> I can't see any useful message. Maybe you should check your configuration file. Also, you need change the output path in the configuration file.

I launch the launch file.However, I meet the problem:Failed to open configuration file.how to solve the problem?

**Comment by thlsealight** [comment]
> > > how to solve this issue
> > 
> > 
> > I can't see any useful message. Maybe you should check your configuration file. Also, you need change the output path in the configuration file.
> 
> I launch the launch file.However, I meet the problem:Failed to open configuration file.how to solve the problem?

Please show your ic_gvins.yaml.

**Comment by bobododosjl** [comment]
# IC-GVINS多源融合定位算法配置文件

# 结果输出路径
# Output directory
outputpath: "outputpath: "/home/bobododo/GNC/SLAM/gvins_ws/src/IC-GVINS-main/output/"
is_make_outputdir: true

# 时间信息, s
# Time length for GNSS/INS intialization
initlength: 1

# IMU原始数据频率, Hz
# IMU sample rate
imudatarate: 100

# 考虑地球自转补偿项
# Consider the Earth rotation
iswithearth: true

# 天线杆臂, IMU前右下方向, m
# GNSS lever-arm in IMU body frame (front-right-down)
antlever: [-0.37, 0.008, 0.353] 

# IMU噪声建模参数
# IMU noise parameters
imumodel:
    arw: 0.1        # deg/sqrt(hr)
    vrw: 0.1        # m/s/sqrt(hr)
    gbstd: 50.0     # deg/hr
    abstd: 50.0     # mGal
    corrtime: 1.0   # hr

# GNSS中断配置
# GNSS outage configurations, the GNSS will not be used after the gnssoutagetime 
isusegnssoutage: false
gnssoutagetime: 364461.5

# 固定阈值GNSS抗差
# A fixed threshold (STD, m) for GNSS outlier culling
gnssthreshold: 5

# 是否开启可视化
# Use visualization
is_use_visualization: true

# 跟踪
# Tracking configurations
track_check_histogram: false    # 直方图检查, 避免出现光照变化较大的图像 (Check histogram for drastic illumulation change)
track_min_parallax: 15          # 关键帧最小像素视差 (The minmum parallax in pixels to choose a keyframe)
track_max_interval: 0.5         # 最大的关键帧间隔, 超过则插入观测帧, s (The maximum lenght to choose a observation frame)
track_max_features: 200         # 最大提取特征数量 (The maximum features to detect, may be more or less, see tracking.cc)

# 优化
# Optimization configurations
reprojection_error_std: 1.5         # 像素重投影误差 (The reprojection error std for optimizition and outlier culling)
optimize_windows_size: 10           # 滑动窗口大小 (The size of the sliding window, number of the keyframes )
optimize_num_iterations: 20         # 优化迭代次数 (The iterations in total)
optimize_estimate_extrinsic: true   # 是否估计相机和IMU的外参 (Estimate the extrinsic)
optimize_estimate_td: true          # 否估计相机和IMU之间的时间间隔 (Estimate the time delay)

# Camera parameters
cam0:
    # 内参 [fx, fy, cx, cy(, skew)]
    # Intrinsic parameters, pinhole model
    intrinsic:
        [
            8.1640221474060002e+02,
            8.1738388562809996e+02,
            6.0882658427579997e+02,
            2.6668865652440002e+02,
            -2.3882017757999998e+00,
        ]

    # 畸变参数 [k1, k2, p1, p2(, k3)]
    # Distortion parameters
    distortion:
        [
            -5.0040485799999999e-02,
            1.2001217170000000e-01,
            -6.2598060000000004e-04,
            -1.1825064000000000e-03,
            -6.3505207999999994e-02,
        ]

    # 图像分辨率
    # Resolution
    resolution: [1280, 560]

    # 相机IMU外参 (Camera-IMU extrinsic)
    # Pb = q_b_c * Pc + t_b_c
    # q (x, y, z, w)
    q_b_c: [0.49452151768306785, 0.4977818081111032, 0.5055845943507494, 0.5020417891144757]
    t_b_c: [1.71239, -0.247401, 0.11589]

    # IMU和相机时间延时 (The time delay between the IMU and camera)
    # t_i = t_c + td
    td_b_c: 0.0

**Comment by bobododosjl** [comment]
> > > > how to solve this issue
> > > 
> > > 
> > > I can't see any useful message. Maybe you should check your configuration file. Also, you need change the output path in the configuration file.
> > 
> > 
> > I launch the launch file.However, I meet the problem:Failed to open configuration file.how to solve the problem?
> 
> Please show your ic_gvins.yaml.

i find the fault

**Comment by thlsealight** [comment]
It seems that the first configuration is wrong.
`outputpath: "outputpath: "/home/bobododo/GNC/SLAM/gvins_ws/src/IC-GVINS-main/output/"`
Maybe the correct configuration is:
`outputpath: "/home/bobododo/GNC/SLAM/gvins_ws/src/IC-GVINS-main/output/"`

**Comment by thlsealight** [comment]
> > > > > how to solve this issue
> > > > 
> > > > 
> > > > I can't see any useful message. Maybe you should check your configuration file. Also, you need change the output path in the configuration file.
> > > 
> > > 
> > > I launch the launch file.However, I meet the problem:Failed to open configuration file.how to solve the problem?
> > 
> > 
> > Please show your ic_gvins.yaml.
> 
> i find the fault

Good! This issue will be closed.
