### ISSUE TITLE
初始化后异常退出

### ISSUE THREAD

**Issue by lqql2012** [i2Nav-WHU/IC-GVINS#30]
你好，我使用官方提供的urban39数据集，始终出现以下报错：

**Comment by lqql2012** [comment]
E0619 03:25:00.397840  4319 ic_gvins.cc:185] Append extra IMU data at 367065.046410
E0619 03:25:00.407724  4319 ic_gvins.cc:175] Lost IMU data with at 367065.061 dt 0.010
E0619 03:25:00.407840  4319 ic_gvins.cc:185] Append extra IMU data at 367065.056408
E0619 03:25:00.417701  4319 ic_gvins.cc:175] Lost IMU data with at 367065.071 dt 0.010
E0619 03:25:00.417807  4319 ic_gvins.cc:185] Append extra IMU data at 367065.066403
E0619 03:25:00.427762  4319 ic_gvins.cc:175] Lost IMU data with at 367065.081 dt 0.010
E0619 03:25:00.427861  4319 ic_gvins.cc:185] Append extra IMU data at 367065.076410
I0619 03:25:00.428071  4343 ic_gvins.cc:646] Initialized pitch from GNSS as 0.0907222 deg
I0619 03:25:00.428155  4343 ic_gvins.cc:649] Initialized heading from GNSS as 82.7548 deg
I0619 03:25:00.428201  4343 misc.cc:220] Redo INS mechanization at 367064.077781 to 367065.076410 is 0.998629 s
I0619 03:25:00.428303  4343 ic_gvins.cc:688] Initialization at 367065.077304
I0619 03:25:00.428324  4343 ic_gvins.cc:894] Add new GNSS time node 367065.077304
[ic_gvins_node-1] process has died [pid 4319, exit code -11, cmd /home/lqql/Auto_Driver/worlplace/gnss_odom/VIO_GNSS_ws/devel/lib/ic_gvins/ic_gvins_ros __name:=ic_gvins_node __log:=/home/lqql/.ros/log/117ebe0c-0e4d-11ee-be78-a4bb6d99f862/ic_gvins_node-1.log].
log file: /home/lqql/.ros/log/117ebe0c-0e4d-11ee-be78-a4bb6d99f862/ic_gvins_node-1*.log

**Comment by lqql2012** [comment]
修改imu 频率后 不会再imu的错误，但是还是报错如下
I0619 05:14:12.647274  4882 ic_gvins.cc:688] Initialization at 367021.081128
I0619 05:14:12.647279  4882 ic_gvins.cc:894] Add new GNSS time node 367021.081128
I0619 05:14:12.657102  4882 misc.cc:220] Redo INS mechanization at 367021.081128 to 367021.093036 is 0.0119085 s
I0619 05:14:13.475628  4855 fusion_ros.cc:232] Raw data time 367021.903006, 367021.081128, 367021.911235
I0619 05:14:13.647060  4882 ic_gvins.cc:894] Add new GNSS time node 367022.080338
I0619 05:14:13.647964  4884 ic_gvins.cc:1854] Total 3 pose states from 367020.080451 to 367022.080338
I0619 05:14:13.649749  4884 ic_gvins.cc:722] Ceres Solver Report: Iterations: 17, Initial cost: 5.419493e+01, Final cost: 9.900459e+00, Termination: CONVERGENCE
I0619 05:14:13.649775  4884 ic_gvins.cc:424] GINS initialization is finished
I0619 05:14:13.649782  4884 ic_gvins.cc:476] Optimization costs 1.84797 ms with 0 and 0 with marginalization costs 0
I0619 05:14:13.657075  4882 misc.cc:220] Redo INS mechanization at 367022.080338 to 367022.093007 is 0.0126691 s
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/core/src/matrix.cpp:423: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function 'Mat'

[ic_gvins_node-1] process has died [pid 4855, exit code -6, cmd /home/lqql/Auto_Driver/worlplace/gnss_odom/VIO_GNSS_ws/devel/lib/ic_gvins/ic_gvins_ros __name:=ic_gvins_node __log:=/home/lqql/.ros/log/117ebe0c-0e4d-11ee-be78-a4bb6d99f862/ic_gvins_node-1.log].
log file: /home/lqql/.ros/log/117ebe0c-0e4d-11ee-be78-a4bb6d99f862/ic_gvins_node-1*.log

**Comment by zhziller** [comment]
请问后面那个报错你有没有解决，用的什么方法
