### ISSUE TITLE
kaist数据集的使用

### ISSUE THREAD

**Issue by Dalingbao** [i2Nav-WHU/IC-GVINS#33]
您好，我使用您提供的数据集都可以跑通，但是使用kaist urban39自己制作的的rosbag，会出现错误，
1）使用gps_fix会报错，这里我发现gps_fix数据是5hz的
OpenCV Error: Assertion failed (0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols) in Mat, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp, line 491
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp:491: error: (-215) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function Mat

[ic_gvins_node-2] process has died [pid 7090, exit code -6, cmd /home/lingyue/gvins_ws/devel/lib/ic_gvins/ic_gvins_ros __name:=ic_gvins_node __log:=/home/lingyue/.ros/log/255db9e4-4d7e-11ee-b091-f48e38f96320/ic_gvins_node-2.log].
log file: /home/lingyue/.ros/log/255db9e4-4d7e-11ee-b091-f48e38f96320/ic_gvins_node-2*.log
2）将rtk的数据转换成sensor_msgs/NavSatFix之后，终端会循环打印
I0907 21:05:11.355453  7636 fusion_ros.cc:232] Raw data time 367215.615833, 0.000000, 367215.613807
但是rviz里是没有反应的，同时我发现kaist的imu数据可能是前左上的，我想咨询一下如何正确地使用kaist的数据

**Comment by thlsealight** [comment]
1）请使用VRS-RTK GPS数据；
2）IMU转成前右下格式，参考README，确保数据时标正确，打印出来的消息显示没有有效GNSS数据；

**Comment by Dalingbao** [comment]
谢谢
