### ISSUE TITLE
Convert back to GNSS data

### ISSUE THREAD

**Issue by quangpham2006** [i2Nav-WHU/IC-GVINS#40]
Thank you so much for the amazing code. However, is that any option that I can convert the fused trajectory back in GNSS msg [sensor_msgs/NavSatFix]. Thank you

**Comment by thlsealight** [comment]
> Thank you so much for the amazing code. However, is that any option that I can convert the fused trajectory back in GNSS msg [sensor_msgs/NavSatFix]. Thank you

Please refer to the function writeNavResult() in misc.cc.
