### ISSUE TITLE
Cannot download the demo datasets (campus.bag, building.bag)

### ISSUE THREAD

**Issue by IaroslavS** [i2Nav-WHU/IC-GVINS#41]
Hi, thanks for your great work !
Unfortunately, I don’t understand Chinese and I can’t download the datasets from the link provided in the Readme.
Could you please upload these rosbags into google cloud ?

**Comment by thlsealight** [comment]
> Hi, thanks for your great work ! Unfortunately, I don’t understand Chinese and I can’t download the datasets from the link provided in the Readme. Could you please upload these rosbags into google cloud ?

Sorry for that. I have no other way to share the datasets. You can directly download the KAIST dataset from their website, and prepare the ROS bag as described in README.

**Comment by IaroslavS** [comment]
> > Hi, thanks for your great work ! Unfortunately, I don’t understand Chinese and I can’t download the datasets from the link provided in the Readme. Could you please upload these rosbags into google cloud ?
> 
> Sorry for that. I have no other way to share the datasets. You can directly download the KAIST dataset from their website, and prepare the ROS bag as described in README.

Could you please share the link to that website with the KAIST dataset ?

**Comment by thlsealight** [comment]
> > > Hi, thanks for your great work ! Unfortunately, I don’t understand Chinese and I can’t download the datasets from the link provided in the Readme. Could you please upload these rosbags into google cloud ?
> > 
> > 
> > Sorry for that. I have no other way to share the datasets. You can directly download the KAIST dataset from their website, and prepare the ROS bag as described in README.
> 
> Could you please share the link to that website with the KAIST dataset ?

https://sites.google.com/view/complex-urban-dataset
