### ISSUE TITLE
Is it possible to run on a UAV's dataset with a downward looking camera ?

### ISSUE THREAD

**Issue by IaroslavS** [i2Nav-WHU/IC-GVINS#42]
Hi, the question as in the title - Is it possible to run on a UAV's dataset ? Or is it adapted only for a UGV ?
In particular, I'm wondering about the dataset ["FGI Masala Stereo-Visual-Inertial Dataset 2021 Dataset tags"](https://etsin.fairdata.fi/dataset/50c898c9-a8f9-4935-80f0-08fc661e88b3). 
Here the camera is pointed down towards the surface of the earth. The dataset also contains imu and gps.
You can have a look at the video of the dataset here https://youtu.be/gGd-oN505mo

**Comment by thlsealight** [comment]
It is absolute that IC-GVINS can run on a UAV's dataset. Please follow the README to prepare the dataset. I can not provide more help.
