### ISSUE TITLE
IMU数据增量转换（KF-GINS）

### ISSUE THREAD

**Issue by Afloat16** [i2Nav-WHU/IC-GVINS#43]
在你们的KF-GINS中，你们的原始数据是线速度和角速度增量，在这个中我们的IMU测量出来的数据是加速度计的加速度，陀螺仪的角速度，我想知道怎么转换为你们的增量的呢？直接时间间隔乘加速度？

**Comment by thlsealight** [comment]
在我们团队的多个仓库提相同的问题是很不礼貌的事情，尤其是在不相关的仓库提及其他仓库的问题。请参考KF-GINS的[issue](https://github.com/i2Nav-WHU/KF-GINS/issues/23)回答。
