### ISSUE TITLE
请问如何运行imu坐标系为右前上的数据集？

### ISSUE THREAD

**Issue by JinXJinLeX** [i2Nav-WHU/IC-GVINS#5]
我们自己的数据集的imu坐标系是右前上，
修改了imucallback函数的这一处:
    imu_.dtheta[0] = imumsg->angular_velocity.y * imu_.dt;
    imu_.dtheta[1] = imumsg->angular_velocity.x * imu_.dt;
    imu_.dtheta[2] = (-1)*imumsg->angular_velocity.z * imu_.dt;
    imu_.dvel[0]   = imumsg->linear_acceleration.y * imu_.dt;
    imu_.dvel[1]   = imumsg->linear_acceleration.x * imu_.dt;
    imu_.dvel[2]   = (-1)*imumsg->linear_acceleration.z * imu_.dt;
但不能成功运行，请问需要做哪些调整，感谢！

**Comment by thlsealight** [comment]
> 我们自己的数据集的imu坐标系是右前上， 修改了imucallback函数的这一处: imu_.dtheta[0] = imumsg->angular_velocity.y * imu_.dt; imu_.dtheta[1] = imumsg->angular_velocity.x * imu_.dt; imu_.dtheta[2] = (-1)*imumsg->angular_velocity.z * imu_.dt; imu_.dvel[0] = imumsg->linear_acceleration.y * imu_.dt; imu_.dvel[1] = imumsg->linear_acceleration.x * imu_.dt; imu_.dvel[2] = (-1)*imumsg->linear_acceleration.z * imu_.dt; 但不能成功运行，请问需要做哪些调整，感谢！

除了调整轴向，外参也要进行对应的调整。
